version: "3.8"

services:
  n8n:
    restart: always
    build: ./n8n
    ports:
      - "10002:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=db
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${N8N_DB_USER}
      - DB_POSTGRESDB_PASSWORD=${N8N_DB_PASSWORD}
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${N8N_BASIC_AUTH_USER}
      - N8N_BASIC_AUTH_PASSWORD=${N8N_BASIC_AUTH_PASSWORD}
      - N8N_CUSTOM_EXTENSIONS=/home/node/custom-nodes
      - N8N_ENCRYPTION_KEY=${N8N_ENCRYPTION_KEY}
      - EVOLUTION_API_INSTANCE_ID=${EVOLUTION_API_INSTANCE_ID}
      - N8N_RUNNERS_ENABLED=true
      - N8N_BLOCK_ENV_ACCESS_IN_NODE=false
      - N8N_GIT_NODE_DISABLE_BARE_REPOS=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./n8n_data:/home/node/.n8n

  redis:
    restart: always
    image: redis:alpine
    command: redis-server --appendonly yes
    volumes:
      - ./redis_data:/data

  evolution-api:
    image: evoapicloud/evolution-api:v2.3.7
    restart: always
    ports:
      - "10003:8080"
    environment:
      - AUTHENTICATION_API_KEY=${AUTHENTICATION_API_KEY}
      - DATABASE_ENABLED=true
      - DATABASE_PROVIDER=postgresql
      - DATABASE_CONNECTION_URI=${DATABASE_CONNECTION_URI}
      - SERVER_URL=${SERVER_URL}
      - CACHE_REDIS_ENABLED=true
      - CACHE_REDIS_URI=${REDIS_URI}
      - CACHE_REDIS_PREFIX_KEY=evolution
      - CACHE_REDIS_SAVE_INSTANCES=true
      - CONFIG_SESSION_PHONE_VERSION=${CONFIG_SESSION_PHONE_VERSION}
    volumes:
      - ./evolution_store:/evolution/store
      - ./evolution_instances:/evolution/instances
    depends_on:
      - db
      - redis

  db:
    restart: always
    image: postgres:16
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

    ports:
      - "10004:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB:-iris_db}",
        ]
      interval: 5s
      timeout: 5s
      retries: 5
